### ISSUE TITLE
Support sources other than Dropbox (any URL ?)

### ISSUE THREAD

**Issue by C-Duv** [mytory/mytory-markdown#2]
I was looking exactly for this kind of plugin (fetch content from external storage and display it into a WordPress article/page) but couldn't find one until now. Rendering markdown is the icing on the cake.

Except the source I am willing to use is GitHub itself (display projects documentations) directly on my WordPress blog.

I think it would be great if this plugin could grab content from any URL (GitHub has URLs that serves raw content) and not only from Dropbox.
##

**Comment by mytory** [comment]
You know, I carried it out. Thanks.
